apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  namespace: default
  labels:
    app: flask-test
spec:
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: data-pvc                                                                                                 
      containers:                                                                                                             
      - name: flask
    image: registry.gitlab.com/narjeskar/build-docker/flask:latest
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: vol
      mountPath: /home/ubuntu/data
  nodeName: worker01
  imagePullSecrets:                                                                                                       
  - name: regcred 
