apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
  name: flask-api
  namespace: default
spec:
  clusterIP: 10.96.147.51
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
  type: ClusterIP
