apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/data/
  claimRef:
    name: data-pvc
    namespace: default
